# Generated by Django 5.2.8 on 2026-03-03 21:55

from datetime import date

from django.db import migrations, models
from django.utils import timezone


def _age_from_birth_date(value: date, today: date) -> int:
    age = today.year - value.year
    if (today.month, today.day) < (value.month, value.day):
        age -= 1
    return age


def migrate_age_to_birth_date(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    today = timezone.now().date()

    for profile in UserProfile.objects.filter(birth_date__isnull=True).exclude(age__isnull=True):
        years = profile.age
        if not years:
            continue

        try:
            derived = date(today.year - years, today.month, today.day)
        except ValueError:
            # Handles February 29 in non-leap target years.
            derived = date(today.year - years, today.month, min(today.day, 28))

        profile.birth_date = derived
        profile.save(update_fields=["birth_date", "updated_at"])


def migrate_birth_date_to_age(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    today = timezone.now().date()

    for profile in UserProfile.objects.exclude(birth_date__isnull=True):
        years = _age_from_birth_date(profile.birth_date, today)
        profile.age = years if 1 <= years <= 120 else None
        profile.save(update_fields=["age", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_age_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_age_to_birth_date, migrate_birth_date_to_age),
        migrations.RemoveField(
            model_name="userprofile",
            name="age",
        ),
    ]
