# Generated by Django 5.2 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_notification_category_expansion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("verification", "Verification"),
                    ("writer_application", "Writer application"),
                    ("content_review", "Content review"),
                    ("follow", "Follow"),
                    ("like", "Like"),
                    ("reaction", "Reaction"),
                    ("comment", "Comment"),
                    ("publication", "Publication"),
                    ("system", "System"),
                ],
                max_length=40,
            ),
        ),
    ]
