# Generated by Django 5.2 on 2026-03-05

from django.db import migrations, models
from django.utils import timezone


def dedupe_pending_writer_applications(apps, schema_editor):
    WriterApplication = apps.get_model("accounts", "WriterApplication")

    pending_rows = (
        WriterApplication.objects.filter(status="pending")
        .order_by("user_id", "-created_at", "-id")
        .values_list("id", "user_id")
    )

    keep_first_by_user = set()
    to_cancel = []
    for app_id, user_id in pending_rows:
        if user_id in keep_first_by_user:
            to_cancel.append(app_id)
            continue
        keep_first_by_user.add(user_id)

    if to_cancel:
        WriterApplication.objects.filter(id__in=to_cancel).update(
            status="canceled",
            reviewed_at=timezone.now(),
            reviewed_by_id=None,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_notification_category_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writerapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(dedupe_pending_writer_applications, noop_reverse),
        migrations.AddConstraint(
            model_name="writerapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user",),
                name="accounts_unique_pending_writer_application_per_user",
            ),
        ),
    ]
