# Generated by Django 5.2 on 2026-03-05

from django.db import migrations, models


def set_default_nationality_for_existing_rows(apps, schema_editor):
    UserProfile = apps.get_model("accounts", "UserProfile")
    UserProfile.objects.filter(nationality__isnull=True).update(nationality="georgian")
    UserProfile.objects.filter(nationality="").update(nationality="georgian")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_writer_application_canceled_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nationality",
            field=models.CharField(blank=True, default="georgian", max_length=120),
        ),
        migrations.RunPython(set_default_nationality_for_existing_rows, noop_reverse),
    ]
