# Generated by Django 5.2.8 on 2026-02-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_book_extracted_text_poem_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/covers/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='poem',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/covers/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/covers/%Y/%m/%d/'),
        ),
    ]
