# Generated by Django 5.2.8 on 2026-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poem',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
