# Generated by Django 5.2.8 on 2026-02-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_book_is_anonymous_poem_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
