# Generated by Django 5.2.8 on 2026-03-01

from django.db import migrations, models
from django.utils.text import slugify


def _next_unique_slug(model, title, used_slugs):
    base = slugify(title or "")[:220] or "work"
    if base.isdigit():
        base = f"work-{base}"
    candidate = base
    index = 2

    while candidate in used_slugs or model.objects.filter(public_slug=candidate).exists():
        suffix = f"-{index}"
        candidate = f"{base[: max(1, 255 - len(suffix))]}{suffix}"
        index += 1

    used_slugs.add(candidate)
    return candidate


def populate_public_slugs(apps, schema_editor):
    for model_name in ("Book", "Poem", "Story"):
        model = apps.get_model("content", model_name)
        used_slugs = set(
            model.objects.exclude(public_slug__isnull=True)
            .exclude(public_slug="")
            .values_list("public_slug", flat=True)
        )

        for obj in model.objects.all().only("id", "title", "public_slug").order_by("id"):
            if obj.public_slug:
                used_slugs.add(obj.public_slug)
                continue
            slug = _next_unique_slug(model, obj.title, used_slugs)
            model.objects.filter(pk=obj.pk).update(public_slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_book_is_hidden_poem_is_hidden_story_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="public_slug",
            field=models.SlugField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poem",
            name="public_slug",
            field=models.SlugField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="story",
            name="public_slug",
            field=models.SlugField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.RunPython(populate_public_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="book",
            name="public_slug",
            field=models.SlugField(blank=True, db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="poem",
            name="public_slug",
            field=models.SlugField(blank=True, db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="public_slug",
            field=models.SlugField(blank=True, db_index=True, max_length=255, unique=True),
        ),
    ]
