# Generated by Django 5.2.8 on 2026-03-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_add_public_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
