# Generated by Django 5.2.8 on 2026-03-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_content_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_submitted_for_review",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="chapter",
            name="is_submitted_for_review",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="poem",
            name="is_submitted_for_review",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="story",
            name="is_submitted_for_review",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
