# Generated by Django 5.2.8 on 2026-03-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_content_submit_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="upload_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="upload_processing_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="book",
            name="upload_processing_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
    ]
