# Generated by Django 5.2.8 on 2026-03-07 20:20

import content.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_book_upload_processing_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="upload_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=content.storage.build_content_upload_storage,
                upload_to="uploads/content/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="poem",
            name="upload_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=content.storage.build_content_upload_storage,
                upload_to="uploads/content/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="upload_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=content.storage.build_content_upload_storage,
                upload_to="uploads/content/%Y/%m/%d/",
            ),
        ),
    ]
