# Generated by Django 5.2.8 on 2026-03-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_content_upload_storage_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_language',
            field=models.CharField(choices=[('en', 'English'), ('ka', 'Georgian')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='poem',
            name='content_language',
            field=models.CharField(choices=[('en', 'English'), ('ka', 'Georgian')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='story',
            name='content_language',
            field=models.CharField(choices=[('en', 'English'), ('ka', 'Georgian')], default='en', max_length=5),
        ),
    ]
