# Generated by Django 5.2 on 2026-03-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorFollow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_authors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ContentComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField()),
                ("body", models.TextField()),
                ("paragraph_index", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ("excerpt", models.TextField(blank=True)),
                ("is_hidden", models.BooleanField(db_index=True, default=False)),
                ("hidden_reason", models.TextField(blank=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("app_label", "content"), ("model__in", ("book", "story", "poem", "chapter"))),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "hidden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_content_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="engagement.contentcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="ContentReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField()),
                ("reaction", models.CharField(choices=[("like", "Like")], default="like", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("app_label", "content"), ("model__in", ("book", "story", "poem", "chapter"))),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ContentViewEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField()),
                ("anon_key", models.CharField(blank=True, max_length=64)),
                ("paragraph_index", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("app_label", "content"), ("model__in", ("book", "story", "poem", "chapter"))),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_view_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ReadingProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveBigIntegerField()),
                ("progress_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("paragraph_index", models.PositiveIntegerField(blank=True, null=True)),
                ("cursor", models.CharField(blank=True, max_length=120)),
                ("completed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("app_label", "content"), ("model__in", ("book", "story", "poem", "chapter"))),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddConstraint(
            model_name="authorfollow",
            constraint=models.UniqueConstraint(fields=("follower", "author"), name="uniq_author_follow"),
        ),
        migrations.AddConstraint(
            model_name="authorfollow",
            constraint=models.CheckConstraint(
                condition=~models.Q(follower=models.F("author")), name="author_follow_no_self_follow"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentreaction",
            constraint=models.UniqueConstraint(
                fields=("user", "content_type", "object_id", "reaction"),
                name="uniq_content_reaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="readingprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "content_type", "object_id"),
                name="uniq_reading_progress",
            ),
        ),
        migrations.AddConstraint(
            model_name="readingprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(progress_percent__gte=0, progress_percent__lte=100),
                name="reading_progress_percent_range",
            ),
        ),
        migrations.AddIndex(
            model_name="authorfollow",
            index=models.Index(fields=["author", "-created_at"], name="idx_follow_author_created"),
        ),
        migrations.AddIndex(
            model_name="authorfollow",
            index=models.Index(fields=["follower", "-created_at"], name="idx_follow_follower_created"),
        ),
        migrations.AddIndex(
            model_name="contentreaction",
            index=models.Index(fields=["content_type", "object_id"], name="idx_react_ct_obj"),
        ),
        migrations.AddIndex(
            model_name="contentreaction",
            index=models.Index(fields=["user", "-created_at"], name="idx_react_user_created"),
        ),
        migrations.AddIndex(
            model_name="contentreaction",
            index=models.Index(
                fields=["content_type", "object_id", "reaction", "-created_at"],
                name="idx_react_ct_obj_reac_created",
            ),
        ),
        migrations.AddIndex(
            model_name="readingprogress",
            index=models.Index(fields=["content_type", "object_id"], name="idx_prog_ct_obj"),
        ),
        migrations.AddIndex(
            model_name="readingprogress",
            index=models.Index(fields=["user", "-updated_at"], name="idx_prog_user_updated"),
        ),
        migrations.AddIndex(
            model_name="readingprogress",
            index=models.Index(fields=["content_type", "object_id", "-updated_at"], name="idx_prog_ct_obj_updated"),
        ),
        migrations.AddIndex(
            model_name="readingprogress",
            index=models.Index(fields=["completed", "-updated_at"], name="idx_prog_completed_updated"),
        ),
        migrations.AddIndex(
            model_name="contentviewevent",
            index=models.Index(fields=["content_type", "object_id"], name="idx_view_ct_obj"),
        ),
        migrations.AddIndex(
            model_name="contentviewevent",
            index=models.Index(fields=["-created_at"], name="idx_view_created"),
        ),
        migrations.AddIndex(
            model_name="contentviewevent",
            index=models.Index(fields=["user", "-created_at"], name="idx_view_user_created"),
        ),
        migrations.AddIndex(
            model_name="contentviewevent",
            index=models.Index(fields=["anon_key", "-created_at"], name="idx_view_anon_created"),
        ),
        migrations.AddIndex(
            model_name="contentviewevent",
            index=models.Index(fields=["content_type", "object_id", "-created_at"], name="idx_view_ct_obj_created"),
        ),
        migrations.AddIndex(
            model_name="contentcomment",
            index=models.Index(fields=["content_type", "object_id"], name="idx_comment_ct_obj"),
        ),
        migrations.AddIndex(
            model_name="contentcomment",
            index=models.Index(fields=["parent", "-created_at"], name="idx_comment_parent_created"),
        ),
        migrations.AddIndex(
            model_name="contentcomment",
            index=models.Index(
                fields=["content_type", "object_id", "paragraph_index", "-created_at"],
                name="idx_comment_ct_obj_para_created",
            ),
        ),
        migrations.AddIndex(
            model_name="contentcomment",
            index=models.Index(fields=["is_hidden", "-created_at"], name="idx_comment_hidden_created"),
        ),
        migrations.AddIndex(
            model_name="contentcomment",
            index=models.Index(fields=["user", "-created_at"], name="idx_comment_user_created"),
        ),
    ]
