# Generated by Django 5.2 on 2026-03-05

from django.db import migrations, models
import django.db.models.deletion


def forward_fill_progress_metadata(apps, schema_editor):
    ReadingProgress = apps.get_model("engagement", "ReadingProgress")
    Chapter = apps.get_model("content", "Chapter")
    ContentType = apps.get_model("contenttypes", "ContentType")

    chapter_ct = ContentType.objects.filter(app_label="content", model="chapter").first()
    if not chapter_ct:
        return

    chapter_ids = set(Chapter.objects.values_list("id", flat=True))
    queryset = ReadingProgress.objects.all().only(
        "id",
        "content_type_id",
        "object_id",
        "paragraph_index",
        "cursor",
        "chapter_id",
        "last_position",
    )
    for progress in queryset.iterator():
        update_fields = []

        metadata = dict(progress.last_position or {})
        if progress.paragraph_index is not None and "paragraph_index" not in metadata:
            metadata["paragraph_index"] = progress.paragraph_index
        if progress.cursor and "cursor" not in metadata:
            metadata["cursor"] = progress.cursor
        if metadata != (progress.last_position or {}):
            progress.last_position = metadata
            update_fields.append("last_position")

        if progress.content_type_id == chapter_ct.id and progress.object_id in chapter_ids and progress.chapter_id != progress.object_id:
            progress.chapter_id = progress.object_id
            update_fields.append("chapter")

        if update_fields:
            progress.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_content_soft_delete"),
        ("engagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingprogress",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reading_progress_entries",
                to="content.chapter",
            ),
        ),
        migrations.AddField(
            model_name="readingprogress",
            name="last_position",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(forward_fill_progress_metadata, migrations.RunPython.noop),
    ]
