# Generated by Django 5.2 on 2026-03-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_comment_anchor_keys(apps, schema_editor):
    ContentComment = apps.get_model("engagement", "ContentComment")

    for comment in ContentComment.objects.filter(anchor_key="").iterator():
        if comment.paragraph_index is not None:
            comment.anchor_key = f"p:{comment.paragraph_index}"
        elif comment.parent_id:
            parent = ContentComment.objects.filter(id=comment.parent_id).only("anchor_key").first()
            comment.anchor_key = (getattr(parent, "anchor_key", "") or "")[:120]
        if comment.anchor_key:
            comment.save(update_fields=["anchor_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0002_reading_progress_last_position_chapter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentcomment",
            name="anchor_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="contentcomment",
            name="anchor_type",
            field=models.CharField(
                choices=[("block", "Block"), ("paragraph", "Paragraph")],
                db_index=True,
                default="paragraph",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReferralVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref_code", models.CharField(db_index=True, max_length=64)),
                ("visitor_id", models.CharField(db_index=True, max_length=120)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "converted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_visits_converted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-first_seen_at"]},
        ),
        migrations.AddConstraint(
            model_name="referralvisit",
            constraint=models.UniqueConstraint(
                fields=("ref_code", "visitor_id"),
                name="uniq_referral_ref_code_visitor",
            ),
        ),
        migrations.AddIndex(
            model_name="contentcomment",
            index=models.Index(
                fields=["content_type", "object_id", "anchor_type", "anchor_key", "-created_at"],
                name="idx_comment_ct_obj_anchor_created",
            ),
        ),
        migrations.AddIndex(
            model_name="readingprogress",
            index=models.Index(
                fields=["content_type", "object_id", "progress_percent", "-updated_at"],
                name="idx_prog_ct_obj_progress_updated",
            ),
        ),
        migrations.AddIndex(
            model_name="referralvisit",
            index=models.Index(fields=["ref_code", "-first_seen_at"], name="idx_ref_visit_code_created"),
        ),
        migrations.AddIndex(
            model_name="referralvisit",
            index=models.Index(fields=["visitor_id", "-first_seen_at"], name="idx_ref_visit_visitor_created"),
        ),
        migrations.AddIndex(
            model_name="referralvisit",
            index=models.Index(fields=["converted_user", "-first_seen_at"], name="idx_ref_visit_converted_created"),
        ),
        migrations.RunPython(backfill_comment_anchor_keys, migrations.RunPython.noop),
    ]
